<?php

return [
    /**
     * The list of keywords which cannot appear in the request value
     */
    "keywords" => [
        "http://",
        "https://",
        "www",
        "ftp://",
        "mailto:",
        "smb://",
        "afp://",
        "file://",
        "gopher://",
        "news://",
        "ssl://",
        "sslv2://",
        "sslv3://",
        "tls://",
        "tcp://",
        "udp://",
        "url=",
        "href=",
        "dating",
        "sex",
        "porn",
        "fuck",
        "free",
        "win",
        "buy",
        "captcha",
        "spam",
        "hello. and bye.",
        "mail.ru",
        "reading this message",
        "reading my message",
        "reading through my message",
        "are whitelisted",
        "great website",
        "late client",
        "ciao a tutti",
        "viagra",
        "cheap",
        "casino",
        "advertising",
        "keyword",
        "promotion",
        "porntubered",
        "ps: how are you?",
        "beautiful models",
        "privet",
        "beautiful girls",
        "best girls",
        "dosug",
        "trustable",
        "look at the",
        "v7bomdefex",
        "what is it -",
        "email marketing",
        "read your site",
        "crypto",
        "cryptography",
        "cryptocurrency",
        "bitcoin",
        "ethereum",
        "dogecoin",
    ],

];
